version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pvc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pvc_user
      POSTGRES_PASSWORD: pvc_pass
      POSTGRES_DB: pvc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
